spring.application.name=api

# Configuración de la base de datos JPA básica
spring.jpa.show-sql=true

#Generación automática del esquema de la base de datos
spring.jpa.hibernate.ddl-auto=update

# Configuracion jwt para la seguridad
# Leemos el secreto de las variables de entorno del sistema. Si no existe, usamos "defaultSecret..." de respaldo para desarrollo local.
jwt.secret=${JWT_SECRET:unSecretoPorDefectoMuyLargoParaDesarrolloLocal1234567890}
jwt.expiration=600000